--회원 상태코드
-- 1. 정상 2. 탈퇴 3. 정지
CREATE TABLE "MEMBER_STATUS" (
	"STATUS_CD"	NUMBER	PRIMARY KEY,
	"STATUS_NM"	VARCHAR2(20)	NULL
);
COMMENT ON COLUMN "MEMBER_STATUS"."STATUS_CD" IS '회원 상태 코드';
COMMENT ON COLUMN "MEMBER_STATUS"."STATUS_NM" IS '회원 상태 이름';

--회원 등급 코드
-- 100: 일반회원
-- 200: 관리자
CREATE TABLE "MEMBER_GRADE" (
	"GRADE_CD"	NUMBER	 PRIMARY KEY,
	"GRADE_NM"	VARCHAR2(20)	NOT NULL
);
COMMENT ON COLUMN "MEMBER_GRADE"."GRADE_CD" IS '회원 등급 코드';
COMMENT ON COLUMN "MEMBER_GRADE"."GRADE_NM" IS '회원 등급 이름';

-- 게시판 코드
-- 10 : 자유게시판 20 : 노하우 게시판 30 : 유기동물 보호소
-- 40 : 문의하기 50 : 자주하는 질문 60 : 이벤트 70: 자랑하기
-- 80 : 유기동물 신고 90:  아이들 근황 100; 산책일지 110 : 공지사항
CREATE TABLE "BOARD_CODE" (
	"BOARD_CD"	NUMBER	PRIMARY KEY,
	"BOARD_NAME"	VARCHAR2(30)		NOT NULL
);
COMMENT ON COLUMN "BOARD_CODE"."BOARD_CD" IS '게시판 코드';
COMMENT ON COLUMN "BOARD_CODE"."BOARD_NAME" IS '게시판 이름';

-- 게시판, 댓글 상태 코드
-- 1: 정상 2: 삭제 3: 블라인드
CREATE TABLE "STATUS" (
	"STATUS_CD"	NUMBER	PRIMARY KEY,
	"STATUS_NM"	VARCHAR2(20)	NOT NULL
);
COMMENT ON COLUMN "STATUS"."STATUS_CD" IS '상태 코드';
COMMENT ON COLUMN "STATUS"."STATUS_NM" IS '상태 이름';


--회원 정보 테이블

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER	PRIMARY KEY,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(200)		NOT NULL,
	"MEMBER_NM"	VARCHAR2(15)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"ENROLL_DT"	DATE	DEFAULT  SYSDATE	NOT NULL,
	"STATUS_CD"	NUMBER	DEFAULT 1  REFERENCES MEMBER_STATUS,
	"GRADE_CD"	NUMBER	 DEFAULT  100  REFERENCES MEMBER_GRADE
);
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '회원 가입일';
COMMENT ON COLUMN "MEMBER"."STATUS_CD" IS '회원 상태 코드';
COMMENT ON COLUMN "MEMBER"."GRADE_CD" IS '회원 등급 코드';

--반려동물 정보 테이블
CREATE TABLE "ANIMAL" (
	"ANIMAL_NO"	NUMBER	PRIMARY KEY,
	"ANIMAL_NAME"	VARCHAR2(20)		NOT NULL,
	"ANIMAL_VARIETY"	VARCHAR2(30)		NOT NULL,
	"ANIMAL_SEX"	NUMBER(1)		NOT NULL,
	"ANIMAL_BIRTH"	DATE		NOT NULL,
	"ANIMAL_PIC"	VARCHAR2(200)		NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER
);
COMMENT ON COLUMN "ANIMAL"."ANIMAL_NO" IS '동물 번호';
COMMENT ON COLUMN "ANIMAL"."ANIMAL_NAME" IS '동물 이름';
COMMENT ON COLUMN "ANIMAL"."ANIMAL_VARIETY" IS '동물 품종';
COMMENT ON COLUMN "ANIMAL"."ANIMAL_SEX" IS '동물 성별';
COMMENT ON COLUMN "ANIMAL"."ANIMAL_BIRTH" IS '동물 생일';
COMMENT ON COLUMN "ANIMAL"."ANIMAL_PIC" IS '동물 프로필';
COMMENT ON COLUMN "ANIMAL"."MEMBER_NO" IS '회원번호';

--반려동물 이미지 테이블
CREATE TABLE "ANIMAL_IMG" (
	"ANIMAL_IMG_NO"	NUMBER	PRIMARY KEY,
	"ANIMAL_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"ANIMAL_IMG_NM"	VARCHAR2(30)		NOT NULL,
	"ANIMAL_IMG_ORIGINAL"	VARCHAR2(100)		NOT NULL,
	"ANIMAL_IMG_LEVEL"	NUMBER		NOT NULL,
	"ANIMAL_NO"	NUMBER	REFERENCES ANIMAL
);

COMMENT ON COLUMN "ANIMAL_IMG"."ANIMAL_IMG_NO" IS '반려동물 이미지 번호';
COMMENT ON COLUMN "ANIMAL_IMG"."ANIMAL_IMG_PATH" IS '반려동물이미지 경로';
COMMENT ON COLUMN "ANIMAL_IMG"."ANIMAL_IMG_NM" IS '반려동물이미지명';
COMMENT ON COLUMN "ANIMAL_IMG"."ANIMAL_IMG_ORIGINAL" IS '원본 반려동물이미지 명';
COMMENT ON COLUMN "ANIMAL_IMG"."ANIMAL_IMG_LEVEL" IS '반려동물이미지 위치 지정값 저장';
COMMENT ON COLUMN "ANIMAL_IMG"."ANIMAL_NO" IS '동물 번호';

--게시판테이블
CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER	PRIMARY KEY,
	"BOARD_TITLE"	VARCHAR2(200)		NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_CD"	NUMBER 	REFERENCES BOARD_CODE,
	"STATUS_CD"	NUMBER DEFAULT 1	REFERENCES  STATUS,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER
);
COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글';
COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '게시글';
COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '게시글';
COMMENT ON COLUMN "BOARD"."BOARD_CD" IS '게시판 코드';
COMMENT ON COLUMN "BOARD"."STATUS_CD" IS '상태 코드';
COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';


--좋아요 테이블
CREATE TABLE "LIKE" (
	"MEMBER_NO"	NUMBER REFERENCES MEMBER,
	"BOARD_NO"	NUMBER REFERENCES BOARD
);
ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"BOARD_NO"
);

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "LIKE"."BOARD_NO" IS '게시글';

--댓글 테이블
CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER	PRIMARY KEY,
	"REPLY_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REPLY_CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER	REFERENCES BOARD,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER,
	"STATUS_CD"	NUMBER DEFAULT 1	REFERENCES STATUS
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글번호';
COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';
COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DT" IS '댓글 작성일';
COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "REPLY"."STATUS_CD" IS '상태 코드';

--게시판 이미지 테이블
CREATE TABLE "BOARD_PIC" (
	"BOARD_PIC_NO"	NUMBER	PRIMARY KEY,
	"BOARD_PIC_PATH"	VARCHAR2(200)		NOT NULL,
	"BOARD_PIC_NM"	VARCHAR2(30)		NOT NULL,
	"BOARD_PIC_ORIGINAL"	VARCHAR2(100)		NOT NULL,
	"BOARD_PIC_LEVEL"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER	REFERENCES BOARD
);

COMMENT ON COLUMN "BOARD_PIC"."BOARD_PIC_NO" IS '게시판 사진 번호';
COMMENT ON COLUMN "BOARD_PIC"."BOARD_PIC_PATH" IS '게시판 사진 경로';
COMMENT ON COLUMN "BOARD_PIC"."BOARD_PIC_NM" IS '게시판 사진명';
COMMENT ON COLUMN "BOARD_PIC"."BOARD_PIC_ORIGINAL" IS '원본게시판이미지명';
COMMENT ON COLUMN "BOARD_PIC"."BOARD_PIC_LEVEL" IS '게시판사진 위지 지정값';
COMMENT ON COLUMN "BOARD_PIC"."BOARD_NO" IS '게시글';

--포인트 적립 테이블
CREATE TABLE "POINT" (
	"POINT_NO"	NUMBER	PRIMARY KEY,
	"POINT_SCORE"	NUMBER	DEFAULT 0	NULL,
	"POINT_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER
);

COMMENT ON COLUMN "POINT"."POINT_NO" IS '포인트 번호';
COMMENT ON COLUMN "POINT"."POINT_SCORE" IS '포인트 점수';
COMMENT ON COLUMN "POINT"."POINT_DATE" IS '포인트 획득 날짜';
COMMENT ON COLUMN "POINT"."MEMBER_NO" IS '회원번호';

--상품 테이블
CREATE TABLE "PRODUCT" (
	"PRODUCT_NO"	NUMBER	PRIMARY KEY,
	"PRODUCT_NAME"	VARCHAR2(50)		NOT NULL,
	"PRODUCT_POINT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_NO" IS '상품 번호';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_NAME" IS '상품이름';
COMMENT ON COLUMN "PRODUCT"."PRODUCT_POINT" IS '상품 포인트';

--상품 교환 테이블
CREATE TABLE "PRODUCT_EXCHANGE" (
	"EXCHANGE_NO"	NUMBER	PRIMARY KEY,
	"EXCHANGE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER,
	"PRODUCT_NO"	NUMBER	REFERENCES PRODUCT
);

COMMENT ON COLUMN "PRODUCT_EXCHANGE"."EXCHANGE_NO" IS '교환 번호';
COMMENT ON COLUMN "PRODUCT_EXCHANGE"."EXCHANGE_DATE" IS '교환 날짜';
COMMENT ON COLUMN "PRODUCT_EXCHANGE"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "PRODUCT_EXCHANGE"."PRODUCT_NO" IS '상품 번호';

CREATE SEQUENCE SEQ_ANIMAL_NO;
CREATE SEQUENCE SEQ_ANIMAL_IMG_NO;
CREATE SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_PIC_NO;
CREATE SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_POINT_NO;
CREATE SEQUENCE SEQ_PRODUCT_NO;
CREATE SEQUENCE SEQ_EXCHANGE_NO;

--회원 상태 코드
INSERT INTO MEMBER_STATUS VALUES(1, '정상');
INSERT INTO MEMBER_STATUS VALUES(2, '탈퇴');
INSERT INTO MEMBER_STATUS VALUES(3, '정지');

--회원 등급 코드
INSERT INTO MEMBER_GRADE VALUES(   100, '일반회원');
INSERT INTO MEMBER_GRADE VALUES(    200, '관리자');

-- 게시판 코드
-- 10 : 자유게시판 20 : 노하우 게시판 30 : 유기동물 보호소
-- 40 : 문의하기 50 : 자주하는 질문 60 : 이벤트 70: 자랑하기
-- 80 : 유기동물 신고 90:  아이들 근황 100; 산책일지 110 : 공지사항
INSERT INTO BOARD_CODE VALUES( 10, '자유게시판');
INSERT INTO BOARD_CODE VALUES( 20, '노하우 게시판');
INSERT INTO BOARD_CODE VALUES( 30, '유기동물 보호소');
INSERT INTO BOARD_CODE VALUES( 40, '문의하기');
INSERT INTO BOARD_CODE VALUES( 50, '자주하는 질문');
INSERT INTO BOARD_CODE VALUES( 60, '이벤트');
INSERT INTO BOARD_CODE VALUES( 70, '자랑하기');
INSERT INTO BOARD_CODE VALUES( 80, '유기동물 신고');
INSERT INTO BOARD_CODE VALUES( 90, '아이들 근황');
INSERT INTO BOARD_CODE VALUES( 100, '산책일지');
INSERT INTO BOARD_CODE VALUES( 110, '공지사항');

-- 게시판, 댓글 상태 코드
-- 1: 정상 2: 삭제 3: 블라인드
INSERT INTO STATUS VALUES( 1, '정상');
INSERT INTO STATUS VALUES( 2, '삭제');
INSERT INTO STATUS VALUES( 3, '블라인드');

--대댓글용 추가코드--
ALTER TABLE "REPLY" ADD "FEEDBACK" NUMBER DEFAULT NULL REFERENCES "REPLY";